# Generated by Django 5.0.4 on 2024-07-06 15:01

import myauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_profile_avatar_profile_email_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=myauth.models.profile_images_directory_path),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
