# Generated by Django 5.0.4 on 2024-07-07 05:06

import myauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_remove_profile_avatar_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to=myauth.models.profile_images_directory_path),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='myauth_profile',
        ),
    ]
