# Generated by Django 5.0.4 on 2024-07-13 17:31

import myauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0004_alter_profile_image_alter_profile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=myauth.models.profile_images_directory_path),
        ),
    ]
