# Generated by Django 5.0.4 on 2024-07-20 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_remove_article_content_remove_article_pub_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='budy',
            new_name='body',
        ),
    ]
